repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace # Trims trailing whitespace.
      - id: check-ast # Checks whether the files parse as valid python.
      - id: check-case-conflict # Checks for files that would conflict in case-insensitive filesystems.
      - id: check-json # Attempts to load all json files to verify syntax
      - id: check-merge-conflict # Check for files that contain merge conflict strings
      - id: check-xml # Attempts to load all xml files to verify syntax
      - id: check-yaml # Attempts to load all yaml files to verify syntax
      - id: end-of-file-fixer # Makes sure files end in a newline and only a newline.
        exclude: '\.graphql$'
      - id: check-symlinks # Checks for symlinks which do not point to anything
      - id: no-commit-to-branch # Protect specific branches from direct checkins (`master` by default)
        stages: [commit]
      - id: debug-statements # Check for debugger imports and py37+ breakpoint() calls in python source
      - id: check-added-large-files # Prevent giant files from being committed

  - repo: https://github.com/Lucas-C/pre-commit-hooks.git
    rev: v1.3.1
    hooks:
      - id: remove-crlf # Replace CRLF end-lines by LF ones before committing
        exclude: '^\.circleci/initial_db\.sql$'

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck

  - repo: local
    # These local hooks try as much as possible to use the existing invoke commands.
    # This is so that we maintain consistency between pre-commit hooks and what is
    # run on CI.
    hooks:
      - id: local-hooks # Run pre-commit with a local configuration file if it exists
        name: local-hooks
        language: system
        entry: bash -c "if test -f .pre-commit-config.local.yaml; then pre-commit run --config .pre-commit-config.local.yaml; fi"
        require_serial: true # Do not try to split files into batches
