palette = 'catppuccin_frappe'
right_format = '$time'

[character]
success_symbol = '[>](bold green)'
error_symbol =  '[>](bold red)'

[aws]
disabled = true

[cmake]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[dart]
disabled = true

[directory]
read_only = " "
truncate_to_repo = true

[docker_context]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[env_var]
disabled = true

[erlang]
disabled = true

[gcloud]
disabled = true

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = '🌱 '
truncation_length = 80

[golang]
disabled = true

[helm]
disabled = true

[java]
disabled = true

[jobs]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[kubernetes]
disabled = true

[lua]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[nodejs]
symbol = "🟢 "
disabled = false

[ocaml]
disabled = true

[openstack]
disabled = true

[package]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[purescript]
disabled = true

[python]
disabled = false
# format = '[${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[shlvl]
disabled = true

[singularity]
disabled = true

[swift]
disabled = true

[vagrant]
disabled = true

[zig]
disabled = true

[username]
format = "[$user]($style)"

[hostname]
format = "$ssh_symbol[$hostname](bright-blue) "
ssh_symbol = "@"

[time]
disabled = false
format = '⌚️[ $time ]($style) '
style = '#7C717F'
time_format = '%T'
time_range = '10:00:00-14:00:00'
utc_time_offset = '+0'

[palettes.catppuccin_frappe]
base = "#303446"
blue = "#8caaee"
crust = "#232634"
flamingo = "#eebebe"
green = "#a6d189"
lavender = "#babbf1"
mantle = "#292c3c"
maroon = "#ea999c"
mauve = "#ca9ee6"
overlay0 = "#737994"
overlay1 = "#838ba7"
overlay2 = "#949cbb"
peach = "#ef9f76"
pink = "#f4b8e4"
red = "#e78284"
rosewater = "#f2d5cf"
sapphire = "#85c1dc"
sky = "#99d1db"
subtext0 = "#a5adce"
subtext1 = "#b5bfe2"
surface0 = "#414559"
surface1 = "#51576d"
surface2 = "#626880"
teal = "#81c8be"
text = "#c6d0f5"
yellow = "#e5c890"
